<%@ Page Title="" Language="C#" MasterPageFile="~/Website/Main.Master" AutoEventWireup="true" CodeBehind="Privacy Policy.aspx.cs" Inherits="E_Shopping.Website.Privacy_Policy" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <!--Page Banner Start-->
    <div class="page-banner" style="background-image: url(assets/images/banner.jpg);">
        <div class="container">
            <div class="page-banner-content text-center">
                <h2 class="title">Checkout</h2>
                <ol class="breadcrumb justify-content-center">
                    <li class="breadcrumb-item"><a href="Default.aspx">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Privacy Policy</li>
                </ol>
            </div>
        </div>
    </div>
    <!--Page Banner End-->
    <div class="checkout-page section-padding-5">
        <div class="container">
            <div class="row">
                <div>
                    <div>
                     <h1 style="text-align: center;">Privacy Policy</h1>
                    </div>
                    <br />
                    <p style="color:black; text-align:center;">
                        AK Culture s Committed to protecting your privacy. The Privacy Policy explains how your personal information is collected, used. This Privacy Policy applies to our website AK Culture . By accessing or using our Service, you signify that you have read, understood and agree to our collection , storage , use and disclosure of your personal information as describe in this Privacy Policy and our Term of Service.
                                        To help explain thing as clearly  as possible in this Privacy Policy, every time of these 
                                        cookies is small amount of data generated by a website and saved by your web browser. It is used to identify  your browser , provide analytics , remember information about you such  as your language preference or login information.
                    </p>
                </div>
            </div>
        </div>
    </div>
</asp:Content>
